language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - CMD=python

matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
  exclude:
    - python: "3.5"
  include:
    - python: "3.5"
      env: CMD="coverage run --source=pynano"

before_install:
  - pip install codecov

install:
  - pip install -e .[test]

script: $CMD setup.py test

after_success:
  - test -e .coverage && codecov

