language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - pip install codecov

install:
  - pip install -e .[test]

script: python setup.py test

after_success:
  - codecov

